name: Visit URL with Proxies

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # This will run the workflow every hour
  workflow_dispatch:  # This allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libxcomposite1 libxrandr2 libgbm1 libpango-1.0-0 libasound2 libgtk-3-0
        python -m pip install --upgrade pip
        pip install requests fake-useragent playwright
        python -m playwright install

    - name: Run visit script
      run: python visit_script.py
