name: Traffic Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow from the Actions tab

jobs:
  run-traffic-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install-deps
          playwright install

      - name: Run traffic bot
        run: |
          python traffic_bot.py



          
