name: Traffic Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow from the Actions tab

jobs:
  run-traffic-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff1 \
            libopus0 \
            libvpx5 \
            libevent-2.1-7 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-gl \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-ugly \
            libharfbuzz-icu0 \
            libhyphen0 \
            libgles2-mesa \
            libx264-163 \
            libflite1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run traffic bot
        run: |
          python traffic_bot.py
